### ISSUE TITLE
Make apostrophe a separator in Solr

### ISSUE THREAD

**Issue by ThomasG77** [betagouv/sirene_as_api#68]
Not representative. Take it as a case to look for later on :) or fix an overall type of issues.

I'm looking for a particular company called "L'ouvre boite 44" in https://entreprise.data.gouv.fr/

When I type `ouvre boite`, autocompletion returns:

* ouvre boite industries
* ouvre boite production
* ouvre boite productions

When I validate the Search ignoring autocompletion, it returns the 6 following results:

* Ouvre-boite
* L ouvre boite
* Ouvre boite industries
* L' ouvre-boite
* Ouvre boite production
* Ass l ouvre boite sud

My issue here is the fact that when I type "L'ouvre", I get "L'ouvre boite 44" in the autocompletion contrary to previous test.

What bother me is the fact that "L'ouvre boite" should be considered identical to "L' ouvre-boite"
I see 2 ways at data level but I don't know what is the right one to avoid/limit side effects elsewhere:
* clean data by removing space between "L' ouvre-boite"
* removing apostrophe to avoid the case when validating with "ouvre boite" and among the 6 results, none match with "L'ouvre boite 44"

If correction is not in fixing input data, I suppose it should be done at index level but I'm not specialist of this part so I do not have an opinion.

**Comment by Samuelfaure** [comment]
Thank you for your issue !

Some company are indeed registered in the INSEE files as "L' ouvre boite", while others are registered with "L'ouvre boite". It isn't very logical but that's how it is in the official files.

We probably wont fix the input data, because I'm not sure we want to divert from the official files, however I'll try to implement a module in the search engine to consider apostrophes as separators (just like whitespace), it might be enough to fix that issue.

We then will have same results for `l'ouvre`, `l ouvre`, l' ouvre`.

I hope this answer your particular issue.
